name: ZAP Scan on FastAPI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install FastAPI and Uvicorn
      run: |
        pip install fastapi uvicorn
        
    - name: Start FastAPI App Locally
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # allow time for the app to start
        
    - name: Create ZAP Config Directory
      run: |
        mkdir -p ${{ github.workspace }}/zap-config
        echo '{}' > ${{ github.workspace }}/zap-config/config
        
    - name: Run ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'http://localhost:8000'
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_action: false
        cmd_options: '-c ${{ github.workspace }}/zap-config/config -config scanner.attackOnStart=true -config scanner.maxRuleDurationInMins=2'
        allow_issue_writing: false  # Don't create GitHub issues
        markdown_report: true  # Create a markdown report
        html_report: true  # Create an HTML report
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          ${{ github.workspace }}/*.html
          ${{ github.workspace }}/*.json
          ${{ github.workspace }}/*.md
        if-no-files-found: warn
