name: ZAP Scan on FastAPI
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install FastAPI and Uvicorn
      run: |
        pip install fastapi uvicorn
        
    - name: Start FastAPI App Locally
      run: |
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # allow time for the app to start
        
    - name: Run ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'http://localhost:8000'
        token: ${{ secrets.GITHUB_TOKEN }}
        fail_action: true
        cmd_options: '-config scanner.attackOnStart=true -config scanner.maxRuleDurationInMins=2'
        
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: owasp-zap-report.html
