# v5
name: ZAP Scan on FastAPI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install FastAPI and Uvicorn
      run: |
        pip install -r requirements.txt

    - name: Start FastAPI App
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10

    - name: Run ZAP Full Scan (no config file)
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        target: 'http://localhost:8000'
        fail_action: false
        cmd_options: >
          -config scanner.attackOnStart=true
          -config scanner.maxRuleDurationInMins=2

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          *.html
          *.json
        if-no-files-found: warn
